eShop.WebApp/Controllers/Components/PagerViewComponent.cs
using eShop.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;

namespace eShop.WebApp.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return await Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShop.WebApp/Controllers/ProductController.cs
using eShop.ApiIntegration.Category;
using eShop.ApiIntegration.Product;
using eShop.Utilities.Contants;
using eShop.ViewModels.Catalog.Categories;
using eShop.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Security.Claims;

namespace eShop.WebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IProductApiClient _productApiClient;
        private readonly ICategoryApiClient _categoryApiClient;
        public ProductController(IConfiguration configuration, IProductApiClient productApiClient, ICategoryApiClient categoryApiClient)
        {
            _configuration = configuration;
            _productApiClient = productApiClient;
            _categoryApiClient = categoryApiClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Category(int id, GetProductRequest request)
        {
            ViewData["baseUrl"] = _configuration.GetValue<string>(SystemConstants.AppSettings.BaseAddress);
            request.categoryId = id;
            request.languageId = CultureInfo.CurrentCulture.Name;
            if (request.pageIndex == 0) request.pageIndex = 1;
            if (request.pageSize == 0) request.pageSize = 10;
            var productResult = await _productApiClient.GetAll(request);
            if (!productResult.success) return BadRequest(productResult.message);

            var categoryResult = await _categoryApiClient.GetById(id, request.languageId);
            var model = new CategoryPageVm() {
                Category = categoryResult.data,
                PagedResultProduct = productResult.data
            };

            return View(model);
        }

        public async Task<IActionResult> Detail(int id)
        {
            ViewData["baseUrl"] = _configuration.GetValue<string>(SystemConstants.AppSettings.BaseAddress);
            var productResult = await _productApiClient.GetById(id, CultureInfo.CurrentCulture.Name);
            if (!productResult.success) return BadRequest(productResult.message);

            var categoryResult = await _categoryApiClient.GetById(productResult.data.CategoryId, CultureInfo.CurrentCulture.Name);
            if (!categoryResult.success) return BadRequest(categoryResult.message);

            var model = new ProductDetailVm()
            {
                Category = categoryResult.data,
                Product = productResult.data
            };

            return View(model);
        }
    }
}

eShop.WebApp/Views/Product/Category.cshtml
@model eShop.ViewModels.Catalog.Categories.CategoryPageVm
@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string culture = CultureInfo.CurrentCulture.Name;
}
<ul class="breadcrumb">
    <li><a href="index.html"><localize>Home</localize></a> <span class="divider">/</span></li>
    <li class="active"><localize>Products Name</localize></li>
</ul>
<h3>@Model.<small class="pull-right"> 40 products are available </small></h3>
<hr class="soft" />
<p>
    Nowadays the lingerie industry is one of the most successful business spheres.We always stay in touch with the latest fashion tendencies - that is why our goods are so popular and we have a great number of faithful customers all over the country.
</p>
<hr class="soft" />
<form class="form-horizontal span6">
    <div class="control-group">
        <label class="control-label alignL">Sort By </label>
        <select>
            <option>Priduct name A - Z</option>
            <option>Priduct name Z - A</option>
            <option>Priduct Stoke</option>
            <option>Price Lowest first</option>
        </select>
    </div>
</form>

<div id="myTab" class="pull-right">
    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
</div>
<br class="clr" />
<div class="tab-content">
    <div class="tab-pane" id="listView">
        @if (Model != null && Model.PagedResultProduct != null && Model.PagedResultProduct.Items != null && Model.PagedResultProduct.Items.Count > 0)
        {
            foreach (var item in Model.PagedResultProduct.Items)
            {
                <div class="row product" data-id="@item.Id">
                    <div class="span2">
                        <img src="@(ViewData["baseUrl"] + "/" + item.ThumbnailImage)" alt="" />
                    </div>
                    <div class="span4">
                        @*     <h3>New | Available</h3>
                <hr class="soft" />*@
                        <h5>@item.Name</h5>
                        @Html.Raw(item.Description)
                        <a class="btn btn-small pull-right" href="product_details.html"><localize>View Details</localize></a>
                        <br class="clr" />
                    </div>
                    <div class="span3 alignR">
                        <div class="form-horizontal qtyFrm">
                            <h3>@item.Price.ToString("n0")</h3>

                            @*     <label class="checkbox">
                    <input type="checkbox">  Adds product to compair
                    </label><br />*@

                            <div class="btn btn-large btn-primary btn-add-product"><localize>Add to</localize><i class="icon-shopping-cart"></i></div>
                            @*<a href="product_details.html" class="btn btn-large"><i class="icon-zoom-in"></i></a>*@

                        </div>
                    </div>
                </div>
                <hr class="soft" />
            }
        }
    </div>

    <div class="tab-pane  active" id="blockView">
        <ul class="thumbnails">

            @if (Model != null && Model.PagedResultProduct != null && Model.PagedResultProduct.Items != null && Model.PagedResultProduct.Items.Count > 0)
            {
                foreach (var item in Model.PagedResultProduct.Items)
                {
                    <li class="span3 product" data-id="@item.Id">
                        <div class="thumbnail">
                            <a href="product_details.html"><img src="@(ViewData["baseUrl"] + item.ThumbnailImage)" alt="" /></a>
                            <div class="caption">
                                <h5>@item.Id: @item.Name</h5>
                                @Html.Raw(item.Details)
                                <div style="text-align:center">
                                    <a class="btn" href="/@culture/@_loc.GetLocalizedString("ProductUrl")/@item.Id"> <i class="icon-zoom-in"></i></a>
                                    <div class="btn btn-add-product"><localize>Add to</localize><i class="icon-shopping-cart"></i></div>
                                    <a class="btn btn-primary" href="#">@item.Price.ToString("n0")</a>
                                </div>
                            </div>
                        </div>
                    </li>
                }
            }
        </ul>
        <hr class="soft" />
    </div>
</div>

@await Component.InvokeAsync("Pager", Model.PagedResultProduct)

@*<div class="pagination">
    <ul>
        <li><a href="#">&lsaquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">...</a></li>
        <li><a href="#">&rsaquo;</a></li>
    </ul>
</div>*@
<br class="clr" />