eShop.AdminApp/Controllers/Components/NavigationViewComponent.cs
using eShop.AdminApp.Models;
using eShop.ApiIntegration.Language;
using eShop.Utilities.Contants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eShop.AdminApp.Controllers.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private readonly ILanguageApiClient _languageApiClient;
        public NavigationViewComponent(ILanguageApiClient languageApiClient)
        {
            _languageApiClient = languageApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var languages = await _languageApiClient.GetAll();
            var currentLanguageId = HttpContext
                .Session
                .GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var items = languages.data.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = currentLanguageId == null ? x.IsDefault : currentLanguageId == x.Id.ToString()
            });

            var navigationVm = new NavigationViewModel()
            {
                CurrentLanguageId = currentLanguageId,
                Languages = items.ToList()
            };

            return View("Default", navigationVm);
        }
    }
}

eShop.AdminApp/Controllers/ProductController.cs
using eShop.ApiIntegration.Category;
using eShop.ApiIntegration.Product;
using eShop.Utilities.Contants;
using eShop.ViewModels.Catalog.Categories;
using eShop.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eShop.AdminApp.Controllers
{
    //[Authorize]
    public class ProductController : BaseController
    {
        private IConfiguration _configuration;
        private ICategoryApiClient _categoryApiClient;
        private IProductApiClient _productApiClient;
        public ProductController(IConfiguration configuration, ICategoryApiClient categoryApiClient, IProductApiClient productApiClient)
        {
            _configuration = configuration;
            _categoryApiClient = categoryApiClient;
            _productApiClient = productApiClient;
        }

        public async Task<IActionResult> Index(GetProductRequest request)
        {
            ViewData["keyword"] = request.keyword;
            ViewData["pageIndex"] = request.pageIndex;
            ViewData["pageSize"] = request.pageSize;

            if (request.pageIndex == 0) request.pageIndex = 1;
            if (request.pageSize == 0) request.pageSize = 10;
            ViewData["Title"] = "Danh sách sản phẩm";
            List<CategoryVm> lst = new List<CategoryVm>();
            request.languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);

            var resultCategories = await _categoryApiClient.GetAll(request.languageId);
            if (resultCategories.success) lst = resultCategories.data;
            ViewData["CategoriesSelectList"] = new SelectList(lst, "Id", "Name", request.categoryId);

            var result = await _productApiClient.GetAll(request);
            if (TempData["successMessage"] != null)
            {
                ViewData["successMessage"] = TempData["successMessage"];
            }

            return View(result.data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["Title"] = "Thêm mới sản phẩm";
            ViewData["SelectCategories"] = await GetSelectCategories(null);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductCreateRequest request)
        {
            ViewData["Title"] = "Thêm mới sản phẩm";
            ViewData["SelectCategories"] = await GetSelectCategories(request.CategoryId);

            if (!ModelState.IsValid) return View();

            request.LanguageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var result = await _productApiClient.Create(request);

            if (result.success)
            {
                TempData["successMessage"] = "Thêm mới thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.message);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Chỉnh sửa sản phẩm";
            var result = await _productApiClient.GetById(id, HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId));
            if (!result.success)
            {
                return BadRequest(result);
            }
            //chuyển từ UserVm => UpdateUserRequet
            ProductUpdateRequest model = new ProductUpdateRequest()
            {
                Id = result.data.Id,
                Name = result.data.Name,
                Description = result.data.Description,
                Details = result.data.Details,
                SeoAlias = result.data.SeoAlias,
                SeoDescription = result.data.SeoDescription,
                SeoTitle = result.data.SeoTitle,
                IsFeatured = result.data.IsFeatured,
                CategoryId = result.data.CategoryId,
            };
            ViewData["SelectCategories"] = await GetSelectCategories(model.CategoryId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductUpdateRequest request)
        {
            ViewData["Title"] = "Chỉnh sửa sản phẩm";
            ViewData["SelectCategories"] = await GetSelectCategories(request?.CategoryId);

            if (!ModelState.IsValid) return View();

            request.LanguageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var result = await _productApiClient.Update(request);

            if (result.success)
            {
                TempData["successMessage"] = "Thêm mới thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.message);

            return View();
        }

        private async Task<SelectList> GetSelectCategories(int? categoryId)
        {
            var lst = new List<CategoryVm>();

            var result = await _categoryApiClient.GetAll(HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId));

            if (result.success) lst = result.data;

            return new SelectList(lst, "Id", "Name", categoryId);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            ViewData["Title"] = "Chỉnh sửa sản phẩm";
            var result = await _productApiClient.GetById(id, HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId));
            if (!result.success)
            {
                return BadRequest(result);
            }
            return View(result.data);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductDeleteRequest request)
        {
            ViewData["Title"] = "Xóa sản phẩm";
            if (!ModelState.IsValid) return View();

            var result = await _productApiClient.Delete(request);

            if (result.success)
            {
                TempData["successMessage"] = "Xóa sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.message);

            return View();
        }

        public async Task<IActionResult> Fake()
        {
            await _productApiClient.Fake();
            return Content("ok");
        }
    }
}

eShop.AdminApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Administrator</title>
    <link href="/css/style.min.css" rel="stylesheet" />
    <link href="/css/styles.css" rel="stylesheet" />
    <script src="/js/fontawesome.all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    @await Component.InvokeAsync("Navigation")
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseUsers" aria-expanded="false" aria-controls="collapseUsers">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Người dùng
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseUsers" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="User" asp-action="Create">Thêm mới</a>
                                <a class="nav-link" asp-controller="User" asp-action="Index">Danh sách</a>
                            </nav>
                        </div>


                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProducts" aria-expanded="false" aria-controls="collapseProducts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Sản phẩm
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseProducts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Product" asp-action="Create">Thêm mới</a>
                                <a class="nav-link" asp-controller="Product" asp-action="Index">Danh sách</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as: @User.Identity.Name</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="/js/jquery-3.6.4.js"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/scripts.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

eShop.AdminApp/Views/Shared/tmp.cshtml
@{
    ViewData["Title"] = @ViewData["Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid px-4">
    <h1 class="mt-4">@ViewData["Title"]</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
        <li class="breadcrumb-item active">@ViewData["Title"]</li>
    </ol>
    <div class="card mb-4">
        <div class="card-header">
            <a class="btn btn-success" asp-action="Index">Về danh sách</a>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    
                </div>
            </div>

        </div>
    </div>
</div>